# Generated by Django 2.2.4 on 2019-08-14 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professional', '0002_auto_20190813_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='教师名字')),
            ],
            options={
                'verbose_name_plural': '布道师',
            },
        ),
        migrations.CreateModel(
            name='TeacherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con', models.CharField(max_length=20, verbose_name='con')),
                ('t_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher', verbose_name='对应教师')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(verbose_name='优先级')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professional.Stage', verbose_name='阶段')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher', verbose_name='布道师')),
            ],
        ),
    ]
