# Generated by Django 2.2.4 on 2019-08-14 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherdata',
            name='t_id',
        ),
        migrations.DeleteModel(
            name='Teacher_stage',
        ),
        migrations.DeleteModel(
            name='TeacherData',
        ),
    ]
