# Generated by Django 2.2.4 on 2019-08-14 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0002_auto_20190813_1424'),
        ('teacher', '0003_auto_20190814_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': '布道师'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=20, verbose_name='教师姓名'),
        ),
        migrations.CreateModel(
            name='TeacherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(max_length=20, verbose_name='代课星期')),
                ('hours', models.CharField(max_length=20, verbose_name='每天课时')),
                ('con', models.CharField(max_length=20, verbose_name='con')),
                ('t_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher', verbose_name='对应教师')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(verbose_name='优先级')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professional.Stage', verbose_name='阶段')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher', verbose_name='布道师')),
            ],
        ),
    ]
