# Generated by Django 2.2.4 on 2019-08-14 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20190814_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherdata',
            name='con',
        ),
    ]
