# Generated by Django 2.2.4 on 2019-08-20 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_remove_teacherdata_con'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherData',
        ),
    ]
