# Generated by Django 2.2.4 on 2019-08-20 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_delete_teacherdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher_stage',
        ),
    ]
