# Generated by Django 2.2.4 on 2019-08-20 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0015_auto_20190820_1318'),
        ('teacher', '0007_delete_teacher_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachstage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0, verbose_name='阶段代课频数')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professional.Stage')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='stages',
            field=models.ManyToManyField(through='teacher.Teachstage', to='professional.Stage'),
        ),
    ]
