# Generated by Django 2.2.4 on 2019-08-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_auto_20190820_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teachtime',
            field=models.IntegerField(default=0, verbose_name='目前安排课时'),
        ),
    ]
