# Generated by Django 2.2.4 on 2019-08-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_teacher_teachtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='classesed',
            field=models.IntegerField(default=0, verbose_name='带课总数'),
        ),
    ]
