# Generated by Django 2.2.4 on 2019-08-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_teacher_classesed'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='state',
            field=models.CharField(default='00000000000000', max_length=20, verbose_name='老师状态'),
        ),
    ]
