# Generated by Django 2.2.4 on 2019-08-13 02:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professional', '0001_initial'),
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='class_hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(max_length=30, verbose_name='班级课时数据表')),
                ('hours', models.CharField(max_length=30, verbose_name='每天上课可升级')),
                ('tercher', models.CharField(max_length=30, verbose_name='老师上课天数')),
                ('tercher2', models.CharField(max_length=30, verbose_name='助教上课天数')),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='班级名称')),
                ('is_teacher2', models.IntegerField(choices=[('0', '不需要助教'), (1, '必须要助教')], default=0, verbose_name='是否需要助教')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开班时间')),
                ('add_date_time', models.DateTimeField(auto_now_add=True)),
                ('update_date_time', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.Area', verbose_name='班级上课地点')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professional.Professional')),
            ],
        ),
    ]
