# Generated by Django 2.2.4 on 2019-08-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_hours',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='class_hours',
            name='weekday',
        ),
        migrations.AddField(
            model_name='class_hours',
            name='week_hours',
            field=models.BinaryField(default=None, max_length=30, verbose_name='每天上下午代课时长'),
        ),
    ]
