# Generated by Django 2.2.4 on 2019-08-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20190813_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name_plural': '班级'},
        ),
    ]
