# Generated by Django 2.2.4 on 2019-08-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_auto_20190819_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='around',
            field=models.IntegerField(default=0, verbose_name='上课周期'),
        ),
        migrations.AddField(
            model_name='classes',
            name='someday',
            field=models.CharField(default='0', max_length=20, verbose_name='哪几天上课'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='is_outside',
            field=models.IntegerField(choices=[(0, '不是校外课程'), (1, '是校外课程')], default=0, verbose_name='是否校外课程'),
        ),
    ]
