# Generated by Django 2.2.4 on 2019-08-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_auto_20190823_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='now_teacher',
            field=models.CharField(default=' ', max_length=20, verbose_name='当前代课老师名字'),
        ),
    ]
