# Generated by Django 2.2.4 on 2019-08-13 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professional',
            options={'verbose_name_plural': '方向分类'},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'verbose_name_plural': '阶段'},
        ),
        migrations.AddField(
            model_name='stage',
            name='p_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='professional.Professional', verbose_name='对应方向'),
        ),
    ]
