# Generated by Django 2.2.4 on 2019-08-16 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0002_auto_20190813_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='阶段名称')),
            ],
        ),
        migrations.CreateModel(
            name='Stage_n_n',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_time', models.IntegerField(default=0, verbose_name='当前阶段进行时长')),
                ('next_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_stage', to='professional.Stage', verbose_name='预测下阶段内容')),
                ('now_stage', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='professional.Stage', verbose_name='当前阶段')),
            ],
        ),
    ]
