# Generated by Django 2.2.4 on 2019-08-16 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0003_aistage_stage_n_n'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stage_n_n',
        ),
    ]
