# Generated by Django 2.2.4 on 2019-08-16 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0004_delete_stage_n_n'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AiStage',
        ),
    ]
