# Generated by Django 2.2.4 on 2019-08-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0005_delete_aistage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pub_stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='共有阶段表')),
                ('long_time', models.IntegerField(default=0, verbose_name='阶段时长')),
            ],
        ),
    ]
