# Generated by Django 2.2.4 on 2019-08-16 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0006_pub_stage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pub_stage',
            options={'verbose_name_plural': '公共阶段'},
        ),
    ]
