# Generated by Django 2.2.4 on 2019-08-16 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0007_auto_20190816_1451'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pub_stage',
        ),
    ]
