# Generated by Django 2.2.4 on 2019-08-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0008_delete_pub_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beforstage', models.CharField(max_length=20)),
                ('level', models.IntegerField(verbose_name='配合优先级')),
            ],
            options={
                'verbose_name_plural': '阶段优先级',
            },
        ),
    ]
