# Generated by Django 2.2.4 on 2019-08-19 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0009_stage_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(verbose_name='配合优先级')),
                ('beforstage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professional.Stage')),
            ],
            options={
                'verbose_name_plural': '阶段优先级',
            },
        ),
        migrations.DeleteModel(
            name='Stage_order',
        ),
    ]
