# Generated by Django 2.2.4 on 2019-08-19 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0010_auto_20190819_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageorder',
            name='afterstage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='afterstage', to='professional.Stage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stageorder',
            name='beforstage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beforstage', to='professional.Stage'),
        ),
    ]
