# Generated by Django 2.2.4 on 2019-08-20 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_delete_teacher_stage'),
        ('professional', '0011_auto_20190819_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='teachstage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0, verbose_name='阶段代课频数')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professional.Stage')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='stage',
            name='teachers',
            field=models.ManyToManyField(through='professional.teachstage', to='teacher.Teacher'),
        ),
    ]
