# Generated by Django 2.2.4 on 2019-08-20 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0014_auto_20190820_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='teachers',
        ),
        migrations.DeleteModel(
            name='teachstage',
        ),
    ]
