# Generated by Django 2.2.4 on 2019-08-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name_plural': ''},
        ),
    ]
