# Generated by Django 2.2.4 on 2019-08-14 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0002_auto_20190813_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name_plural': '地点'},
        ),
    ]
