# Generated by Django 2.2.4 on 2019-08-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_week', models.CharField(max_length=200, verbose_name='下周课程数据')),
                ('second_week', models.CharField(max_length=200, verbose_name='下下周课程数据')),
                ('third_week', models.CharField(max_length=200, verbose_name='下下下周课程数据')),
            ],
        ),
    ]
