# Generated by Django 2.2.4 on 2019-08-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190821_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_week',
            name='first_week',
            field=models.CharField(max_length=200, verbose_name='下周课程数据'),
        ),
        migrations.AlterField(
            model_name='course_week',
            name='second_week',
            field=models.CharField(max_length=200, verbose_name='下下周课程数据'),
        ),
        migrations.AlterField(
            model_name='course_week',
            name='third_week',
            field=models.CharField(max_length=200, verbose_name='下下下周课程数据'),
        ),
    ]
